# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0004_auto_20161215_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUpDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sex', models.IntegerField()),
                ('telphone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('checked_status', models.IntegerField()),
                ('signup_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='ChoosedLoginParts',
            new_name='ChoosedSignUpParts',
        ),
        migrations.RenameModel(
            old_name='UserLoginExtendAccomodation',
            new_name='UserSignUpExtendAccomodation',
        ),
        migrations.RenameModel(
            old_name='UserLoginExtendAddress',
            new_name='UserSignUpExtendAddress',
        ),
        migrations.RenameModel(
            old_name='UserLoginExtendCompanyInfo',
            new_name='UserSignUpExtendCompanyInfo',
        ),
        migrations.RenameModel(
            old_name='UserLoginExtendCost',
            new_name='UserSignUpExtendCost',
        ),
        migrations.RenameModel(
            old_name='UserLoginExtendExtraInfo',
            new_name='UserSignUpExtendExtraInfo',
        ),
        migrations.RenameModel(
            old_name='UserLoginExtendMailcode',
            new_name='UserSignUpExtendMailcode',
        ),
        migrations.RemoveField(
            model_name='userlogindetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='usersignupextendaccomodation',
            name='basicInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.UserSignUpDetail'),
        ),
        migrations.AlterField(
            model_name='usersignupextendaddress',
            name='basicInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.UserSignUpDetail'),
        ),
        migrations.AlterField(
            model_name='usersignupextendcompanyinfo',
            name='basicInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.UserSignUpDetail'),
        ),
        migrations.AlterField(
            model_name='usersignupextendcost',
            name='basicInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.UserSignUpDetail'),
        ),
        migrations.AlterField(
            model_name='usersignupextendextrainfo',
            name='basicInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.UserSignUpDetail'),
        ),
        migrations.AlterField(
            model_name='usersignupextendmailcode',
            name='basicInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wechat.UserSignUpDetail'),
        ),
        migrations.DeleteModel(
            name='UserLoginDetail',
        ),
    ]
