# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0005_auto_20161215_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersignupdetail',
            name='confid',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='pageNum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pageState',
            field=models.IntegerField(null=True),
        ),
    ]
