# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0006_auto_20161217_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confid', models.CharField(max_length=128)),
                ('detail', models.CharField(max_length=512)),
                ('publish_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='searchWords',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='reminds',
            name='info',
            field=models.CharField(max_length=512),
        ),
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wechat.User'),
        ),
    ]
