# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-22 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0007_auto_20161222_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='system_id',
            new_name='userid',
        ),
    ]
