# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-23 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0008_auto_20161222_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignupextendmailcode',
            old_name='email_code',
            new_name='postcode',
        ),
        migrations.AddField(
            model_name='user',
            name='headimgurl',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='union_id',
            field=models.CharField(db_index=True, default='1', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
