# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-28 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0009_auto_20161223_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSignUpExtendAccomodation',
            new_name='UserSignUpExtendAccommodation',
        ),
        migrations.RenameModel(
            old_name='UserSignUpExtendMailcode',
            new_name='UserSignUpExtendPostcode',
        ),
        migrations.RenameField(
            model_name='priceinfo',
            old_name='price_discription',
            new_name='price_description',
        ),
        migrations.RenameField(
            model_name='usersignupdetail',
            old_name='telphone',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='usersignupextendaccommodation',
            old_name='accomodation_type',
            new_name='accommodation_type',
        ),
        migrations.RenameField(
            model_name='usersignupextendextrainfo',
            old_name='extra_discription',
            new_name='extra_description',
        ),
    ]
