# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-31 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0010_auto_20161228_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='choosedsignupparts',
            name='maxJoinNum',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
